#!/bin/bash

# Function to check if a command was successful
check_command_success() {
    if [ "$1" -ne 0 ]; then
        echo "Error executing command: $2"
        exit 1
    fi
}

# Function to install required packages
install_requirements() {
    # Determine the Linux distribution
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DISTRO=$ID
    elif type lsb_release >/dev/null 2>&1; then
        DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
    else
        DISTRO=$(uname -s)
    fi

    # Normalize distro names to lowercase
    DISTRO=$(echo "$DISTRO" | tr '[:upper:]' '[:lower:]')

    case "$DISTRO" in
        "debian"|"ubuntu"|"kali"|"raspbian")
            required_packages=("jq" "libkf5coreaddons-bin" "kpackagetool5")
            ;;
        "arch"|"manjaro")
            required_packages=("jq" "kcoreaddons" "kpackagetool5")
            ;;
        "fedora")
            required_packages=("jq" "kf5-kcoreaddons" "kf5-kpackage")
            ;;
        *)
            echo "Unsupported distribution: $DISTRO"
            exit 1
            ;;
    esac

    # Install required packages
    echo "Checking and installing required packages..."
    for pkg in "${required_packages[@]}"; do
        if ! command -v $pkg &> /dev/null; then
            echo "$pkg is not installed. Attempting to install..."
            case "$DISTRO" in
                "debian"|"ubuntu"|"kali"|"raspbian")
                    sudo apt-get update && sudo apt-get install -y $pkg
                    ;;
                "arch"|"manjaro")
                    sudo pacman -Sy $pkg
                    ;;
                "fedora")
                    sudo dnf install -y $pkg
                    ;;
            esac
            check_command_success "$?" "Installation of $pkg failed"
        fi
    done
}

# Install script requirements
install_requirements

# Parse arguments for restart option
restartPlasmashell=false
for arg in "$@"; do
    case "$arg" in
        -r|--restart)
            restartPlasmashell=true
            ;;
        *)
            ;;
    esac
done

# Determine if the package is already installed and prepare package installation
metadataFile="$PWD/package/metadata.desktop"
metadataJsonFile="$PWD/package/metadata.json"

# Check for metadata and convert if necessary
if [ -f "$metadataFile" ]; then
    # Plasma 5 compatibility
    packageNamespace=$(kreadconfig5 --file="$metadataFile" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")
    packageServiceType=$(kreadconfig5 --file="$metadataFile" --group="Desktop Entry" --key="X-KDE-ServiceTypes")
elif [ -f "$metadataJsonFile" ]; then
    # Plasma 6 compatibility
    packageNamespace=$(jq -r '.KPlugin.Id' "$metadataJsonFile")
    packageServiceType="Plasma/Applet"
    if [ -z "$packageNamespace" ]; then
        echo "Error: Unable to read the package namespace from metadata.json."
        exit 1
    fi
else
    echo "Error: No compatible metadata file found in the package directory."
    exit 1
fi

kpackagetool5 --type="${packageServiceType}" --show="$packageNamespace" &> /dev/null
isAlreadyInstalled=$?

# Install or update the package
if [ "$isAlreadyInstalled" -eq 0 ]; then
    echo "Updating package: $packageNamespace"
    kpackagetool5 -t "${packageServiceType}" -u package
    check_command_success "$?" "Package update failed"
else
    echo "Installing package: $packageNamespace"
    kpackagetool5 -t "${packageServiceType}" -i package
    check_command_success "$?" "Package installation failed"
fi

# Restart Plasma shell if required
if $restartPlasmashell; then
    kquitapp5 plasmashell && kstart5 plasmashell
    check_command_success "$?" "Failed to restart Plasma shell"
fi

